
<header>
        <nav>
            <div class="dropdown">
                <button class="drop"> <img src="./images/logo.png" alt="menu"></button>
                <div class="dropdown-content">
                    <a href="index.html">Home</a>
                    <a href="jobs.html">Jobs Descriptions</a>
                    <a href="apply.html">Applications</a>
                    <a href="enhancements.html">Enhancements</a>
                    <a href="about.html">About Us</a>
                </div>
        </nav>
    </header>